# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'credit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 826)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 826))
        MainWindow.setMaximumSize(QtCore.QSize(1040, 826))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_window = QtWidgets.QFrame(self.centralwidget)
        self.main_window.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.main_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_window.setObjectName("main_window")
        self.secondary_window = QtWidgets.QFrame(self.main_window)
        self.secondary_window.setGeometry(QtCore.QRect(0, 0, 331, 811))
        self.secondary_window.setStyleSheet("QFrame {\n"
"    background-color: rgb(33, 115, 70);\n"
"}")
        self.secondary_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.secondary_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.secondary_window.setObjectName("secondary_window")
        self.credits_text = QtWidgets.QLabel(self.secondary_window)
        self.credits_text.setGeometry(QtCore.QRect(70, 50, 161, 51))
        self.credits_text.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 650 36pt \"Segoe UI\";\n"
"}")
        self.credits_text.setObjectName("credits_text")
        self.author_text = QtWidgets.QLabel(self.secondary_window)
        self.author_text.setGeometry(QtCore.QRect(30, 150, 251, 51))
        self.author_text.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}")
        self.author_text.setObjectName("author_text")
        self.program_text = QtWidgets.QLabel(self.secondary_window)
        self.program_text.setGeometry(QtCore.QRect(20, 220, 251, 51))
        self.program_text.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}")
        self.program_text.setObjectName("program_text")
        self.program_text_2 = QtWidgets.QLabel(self.secondary_window)
        self.program_text_2.setGeometry(QtCore.QRect(150, 270, 161, 31))
        self.program_text_2.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}")
        self.program_text_2.setObjectName("program_text_2")
        self.github_button = QtWidgets.QPushButton(self.secondary_window)
        self.github_button.setGeometry(QtCore.QRect(10, 740, 91, 61))
        self.github_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(253, 253, 253);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.github_button.setObjectName("github_button")
        self.contact_button = QtWidgets.QPushButton(self.secondary_window)
        self.contact_button.setGeometry(QtCore.QRect(120, 740, 101, 61))
        self.contact_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(253, 253, 253);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.contact_button.setObjectName("contact_button")
        self.license_button = QtWidgets.QPushButton(self.secondary_window)
        self.license_button.setGeometry(QtCore.QRect(240, 740, 81, 61))
        self.license_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(253, 253, 253);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.license_button.setObjectName("license_button")
        self.pushButton = QtWidgets.QPushButton(self.main_window)
        self.pushButton.setGeometry(QtCore.QRect(970, 0, 51, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    font: 500 23pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(235, 0, 0);\n"
"    color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.main_window)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 0, 51, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    font: 100 38pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(179, 179, 179)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.instruction_text = QtWidgets.QLabel(self.main_window)
        self.instruction_text.setGeometry(QtCore.QRect(540, 50, 271, 51))
        self.instruction_text.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(33, 115, 70);\n"
"    font: 650 36pt \"Segoe UI\";\n"
"}")
        self.instruction_text.setObjectName("instruction_text")
        self.instruction_text_2 = QtWidgets.QTextBrowser(self.main_window)
        self.instruction_text_2.setGeometry(QtCore.QRect(380, 160, 601, 561))
        self.instruction_text_2.setObjectName("instruction_text_2")
        self.contact_button_2 = QtWidgets.QPushButton(self.main_window)
        self.contact_button_2.setGeometry(QtCore.QRect(470, 740, 431, 61))
        self.contact_button_2.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(49, 173, 105);\n"
"}\n"
"\n"
"")
        self.contact_button_2.setObjectName("contact_button_2")
        self.verticalLayout.addWidget(self.main_window)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Credits"))
        self.credits_text.setText(_translate("MainWindow", "Credits"))
        self.author_text.setText(_translate("MainWindow", "Author: Fishappy0"))
        self.program_text.setText(_translate("MainWindow", "Program: Student "))
        self.program_text_2.setText(_translate("MainWindow", "Randomizer"))
        self.github_button.setText(_translate("MainWindow", "GitHub"))
        self.contact_button.setText(_translate("MainWindow", "Contact"))
        self.license_button.setText(_translate("MainWindow", "License"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.instruction_text.setText(_translate("MainWindow", "Instructions"))
        self.instruction_text_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#217346;\">At The Main Menu</span><span style=\" font-size:16pt; color:#217346;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">Step 1) Select the import folder with all the excel files needed to be generated</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">Step 2) Select the export destination folder</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">Step 3) Generate !</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#217346;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#217346;\">At The Generation Menu</span><span style=\" font-size:16pt; color:#217346;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">- The &quot;File Name&quot; column shows the name of the files that are being processed</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">- The &quot;Status&quot; column shows the status of the files that are being processed</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">- The &quot;Re-run&quot; button, deletes all the generated files and start the generation process again</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#217346;\">- The &quot;Show Error&quot; button, shows the list of files that had errors after the generation process</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#217346;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#217346;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#217346;\">Notes</span><span style=\" font-size:16pt; color:#217346;\">: Information about files formatting can be found in the format instructions</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#217346;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#217346;\">Video Instruction Link</span><span style=\" font-size:16pt; color:#217346;\">: youtube.com</span></p></body></html>"))
        self.contact_button_2.setText(_translate("MainWindow", "See format instructions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
