# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generating_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Generating(object):
    def setupUi(self, Generating):
        Generating.setObjectName("Generating")
        Generating.resize(1038, 818)
        Generating.setMinimumSize(QtCore.QSize(1038, 818))
        Generating.setMaximumSize(QtCore.QSize(1038, 818))
        self.main_frame = QtWidgets.QWidget(Generating)
        self.main_frame.setMinimumSize(QtCore.QSize(1038, 818))
        self.main_frame.setMaximumSize(QtCore.QSize(1038, 818))
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_window = QtWidgets.QFrame(self.main_frame)
        self.main_window.setStyleSheet("QFrame {\n"
"    background-color: rgb(33, 115, 70);\n"
"}")
        self.main_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_window.setObjectName("main_window")
        self.secondary_window = QtWidgets.QFrame(self.main_window)
        self.secondary_window.setGeometry(QtCore.QRect(0, 260, 1021, 541))
        self.secondary_window.setMinimumSize(QtCore.QSize(1021, 541))
        self.secondary_window.setMaximumSize(QtCore.QSize(1021, 541))
        self.secondary_window.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.secondary_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.secondary_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.secondary_window.setObjectName("secondary_window")
        self.file_list_box = QtWidgets.QTableView(self.secondary_window)
        self.file_list_box.setGeometry(QtCore.QRect(70, 90, 291, 321))
        self.file_list_box.setObjectName("file_list_box")
        self.status_list_box = QtWidgets.QTableView(self.secondary_window)
        self.status_list_box.setGeometry(QtCore.QRect(380, 90, 551, 321))
        self.status_list_box.setObjectName("status_list_box")
        self.cancel_button = QtWidgets.QPushButton(self.secondary_window)
        self.cancel_button.setGeometry(QtCore.QRect(380, 440, 241, 71))
        self.cancel_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(49, 173, 105);\n"
"}\n"
"\n"
"")
        self.cancel_button.setObjectName("cancel_button")
        self.rerun_button = QtWidgets.QPushButton(self.secondary_window)
        self.rerun_button.setGeometry(QtCore.QRect(190, 440, 171, 71))
        self.rerun_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(49, 173, 105);\n"
"}\n"
"\n"
"")
        self.rerun_button.setObjectName("rerun_button")
        self.rerun_button_2 = QtWidgets.QPushButton(self.secondary_window)
        self.rerun_button_2.setGeometry(QtCore.QRect(640, 440, 171, 71))
        self.rerun_button_2.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(49, 173, 105);\n"
"}\n"
"\n"
"")
        self.rerun_button_2.setObjectName("rerun_button_2")
        self.label_2 = QtWidgets.QLabel(self.secondary_window)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 551, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    border-style: none;\n"
"    align: center;\n"
"    font: 550 22px \"Segoe UI\";\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.secondary_window)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 291, 51))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(33, 115, 70);\n"
"    color: white;\n"
"    border-style: none;\n"
"    align: center;\n"
"    font: 550 22px \"Segoe UI\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.progress_bar = QtWidgets.QProgressBar(self.main_window)
        self.progress_bar.setGeometry(QtCore.QRect(270, 140, 461, 51))
        self.progress_bar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(236, 236, 236);\n"
"    color: rgb(88, 88, 88);\n"
"    border-style: none;\n"
"    text-align: center;\n"
"    font: 500 20px \"Segoe UI\";\n"
"}\n"
"QProgressBar::chunk{\n"
"    border: none;\n"
"    qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(210, 254, 210, 255), stop:0.943182 rgba(8, 182, 86, 254));\n"
"}")
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.close = QtWidgets.QPushButton(self.main_window)
        self.close.setGeometry(QtCore.QRect(960, 0, 61, 41))
        self.close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"color: white;\n"
"    font: 500 23pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(235, 0, 0);\n"
"    color: white;\n"
"}")
        self.close.setObjectName("close")
        self.minimize = QtWidgets.QPushButton(self.main_window)
        self.minimize.setGeometry(QtCore.QRect(910, 0, 51, 41))
        self.minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 100 38pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(130, 198, 164);\n"
"}")
        self.minimize.setObjectName("minimize")
        self.label = QtWidgets.QLabel(self.main_window)
        self.label.setGeometry(QtCore.QRect(320, 30, 371, 91))
        self.label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 650 36pt \"Segoe UI\";\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.main_window)
        Generating.setCentralWidget(self.main_frame)

        self.retranslateUi(Generating)
        QtCore.QMetaObject.connectSlotsByName(Generating)

    def retranslateUi(self, Generating):
        _translate = QtCore.QCoreApplication.translate
        Generating.setWindowTitle(_translate("Generating", "Generating"))
        self.cancel_button.setText(_translate("Generating", "Return to menu"))
        self.rerun_button.setText(_translate("Generating", "Re-Run"))
        self.rerun_button_2.setText(_translate("Generating", "Show Errors"))
        self.label_2.setText(_translate("Generating", "Status"))
        self.label_3.setText(_translate("Generating", "File Name"))
        self.close.setText(_translate("Generating", "X"))
        self.minimize.setText(_translate("Generating", "-"))
        self.label.setText(_translate("Generating", "Generating Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Generating = QtWidgets.QMainWindow()
    ui = Ui_Generating()
    ui.setupUi(Generating)
    Generating.show()
    sys.exit(app.exec_())
