# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_student_randomizer_main(object):
    def setupUi(self, student_randomizer_main):
        student_randomizer_main.setObjectName("student_randomizer_main")
        student_randomizer_main.resize(1028, 462)
        student_randomizer_main.setMinimumSize(QtCore.QSize(1028, 462))
        student_randomizer_main.setMaximumSize(QtCore.QSize(1028, 462))
        student_randomizer_main.setStyleSheet("QMainWindow {\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.main_frame = QtWidgets.QWidget(student_randomizer_main)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_window = QtWidgets.QFrame(self.main_frame)
        self.main_window.setStyleSheet("QFrame{\n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.main_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_window.setObjectName("main_window")
        self.secondary_window = QtWidgets.QFrame(self.main_window)
        self.secondary_window.setGeometry(QtCore.QRect(0, 139, 1011, 311))
        self.secondary_window.setStyleSheet("QFrame{\n"
"    background-color: rgb(33, 115, 70);\n"
"}")
        self.secondary_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.secondary_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.secondary_window.setObjectName("secondary_window")
        self.import_text_box = QtWidgets.QLineEdit(self.secondary_window)
        self.import_text_box.setGeometry(QtCore.QRect(310, 50, 511, 41))
        self.import_text_box.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    padding-left: 15px;\n"
"    color: rgb(102, 102, 102);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"")
        self.import_text_box.setObjectName("import_text_box")
        self.export_text_box = QtWidgets.QLineEdit(self.secondary_window)
        self.export_text_box.setGeometry(QtCore.QRect(310, 140, 511, 41))
        self.export_text_box.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    padding-left: 15px;\n"
"    color: rgb(102, 102, 102);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}")
        self.export_text_box.setObjectName("export_text_box")
        self.import_button = QtWidgets.QPushButton(self.secondary_window)
        self.import_button.setGeometry(QtCore.QRect(820, 50, 101, 41))
        self.import_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(233, 233, 233);\n"
"    color: rgb(110, 110, 110);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.import_button.setObjectName("import_button")
        self.export_button = QtWidgets.QPushButton(self.secondary_window)
        self.export_button.setGeometry(QtCore.QRect(820, 140, 101, 41))
        self.export_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(233, 233, 233);\n"
"    color: rgb(110, 110, 110);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.export_button.setObjectName("export_button")
        self.generate_button = QtWidgets.QPushButton(self.secondary_window)
        self.generate_button.setGeometry(QtCore.QRect(380, 200, 271, 81))
        self.generate_button.setStyleSheet("QPushButton{\n"
"    border: 5px;\n"
"    background-color: rgb(253, 253, 253);\n"
"    font: 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 224);\n"
"}\n"
"\n"
"")
        self.generate_button.setObjectName("generate_button")
        self.import_title = QtWidgets.QLabel(self.secondary_window)
        self.import_title.setGeometry(QtCore.QRect(80, 50, 231, 41))
        self.import_title.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}")
        self.import_title.setObjectName("import_title")
        self.export_title = QtWidgets.QLabel(self.secondary_window)
        self.export_title.setGeometry(QtCore.QRect(80, 140, 221, 41))
        self.export_title.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color:white;\n"
"    font: 550 22pt \"Segoe UI\";\n"
"}")
        self.export_title.setObjectName("export_title")
        self.minimize = QtWidgets.QPushButton(self.main_window)
        self.minimize.setGeometry(QtCore.QRect(910, 0, 51, 41))
        self.minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    font: 100 38pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(179, 179, 179)\n"
"}")
        self.minimize.setObjectName("minimize")
        self.close = QtWidgets.QPushButton(self.main_window)
        self.close.setGeometry(QtCore.QRect(960, 0, 51, 41))
        self.close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    font: 500 23pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(235, 0, 0);\n"
"    color: white;\n"
"}")
        self.close.setObjectName("close")
        self.minimize_2 = QtWidgets.QPushButton(self.main_window)
        self.minimize_2.setGeometry(QtCore.QRect(860, 0, 51, 41))
        self.minimize_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    font: 500 22pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(179, 179, 179)\n"
"}")
        self.minimize_2.setObjectName("minimize_2")
        self.title_1 = QtWidgets.QLabel(self.main_window)
        self.title_1.setGeometry(QtCore.QRect(280, 40, 171, 81))
        self.title_1.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(33, 115, 70);\n"
"    font: 450 36pt \"Segoe UI\";\n"
"}")
        self.title_1.setObjectName("title_1")
        self.title_2 = QtWidgets.QLabel(self.main_window)
        self.title_2.setGeometry(QtCore.QRect(460, 40, 281, 81))
        self.title_2.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(33, 115, 70);\n"
"    font: 650 36pt \"Segoe UI\";\n"
"}")
        self.title_2.setObjectName("title_2")
        self.verticalLayout.addWidget(self.main_window)
        student_randomizer_main.setCentralWidget(self.main_frame)

        self.retranslateUi(student_randomizer_main)
        QtCore.QMetaObject.connectSlotsByName(student_randomizer_main)

    def retranslateUi(self, student_randomizer_main):
        _translate = QtCore.QCoreApplication.translate
        student_randomizer_main.setWindowTitle(_translate("student_randomizer_main", "Student Randomizer"))
        self.import_text_box.setText(_translate("student_randomizer_main", "./import"))
        self.export_text_box.setText(_translate("student_randomizer_main", "./export"))
        self.import_button.setText(_translate("student_randomizer_main", "Browse"))
        self.export_button.setText(_translate("student_randomizer_main", "Browse"))
        self.generate_button.setText(_translate("student_randomizer_main", "Generate"))
        self.import_title.setText(_translate("student_randomizer_main", "Import Directory"))
        self.export_title.setText(_translate("student_randomizer_main", "Export Directory"))
        self.minimize.setText(_translate("student_randomizer_main", "-"))
        self.close.setText(_translate("student_randomizer_main", "X"))
        self.minimize_2.setText(_translate("student_randomizer_main", "?"))
        self.title_1.setText(_translate("student_randomizer_main", "Student"))
        self.title_2.setText(_translate("student_randomizer_main", "Randomizer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    student_randomizer_main = QtWidgets.QMainWindow()
    ui = Ui_student_randomizer_main()
    ui.setupUi(student_randomizer_main)
    student_randomizer_main.show()
    sys.exit(app.exec_())
